#!/bin/bash

# clone the repo and run:
# ./boostrap
# This is a one time only run file

# Force a build
touch Gemfile.lock && docker-compose build

# Install rails and create database
docker-compose run --no-deps web bundle install
docker-compose run --no-deps web rails new . --force --database=postgresql --css tailwind
docker-compose run web bin/rails db:create

# Install tailwind (skip if needed) More Info: https://tailwindcss.com/docs/guides/ruby-on-rails
docker-compose run --no-deps web ./bin/rails tailwindcss:install

# Remove this file
rm bootstrap

# Start the application
docker-compose up
